export enum ChildPlan {
  WANT_CHILDREN = 'WANT_CHILDREN',

  DONT_WANT_CHILDREN = 'DONT_WANT_CHILDREN',

  HAVE_CHILDREN_AND_WANT_MORE = 'HAVE_CHILDREN_AND_WANT_MORE',

  HAVE_CHILDREN_AND_DONT_WANT_MORE = 'HAVE_CHILDREN_AND_DONT_WANT_MORE',

  NOT_SURE_YET = 'NOT_SURE_YET',
}
