export enum Education {
  PRIMARY_EDUCATION = 'PRIMARY_EDUCATION',

  SECONDARY_EDUCATION = 'SECONDARY_EDUCATION',

  INCOMPLETE_HIGHER_BACHELOR_EDUCATION = 'INCOMPLETE_HIGHER_BACHELOR_EDUCATION',

  COMPLETE_HIGHER_BACHELOR_EDUCATION = 'COMPLETE_HIGHER_BACHELOR_EDUCATION',

  INCOMPLETE_HIGHER_MASTER_EDUCATION = 'INCOMPLETE_HIGHER_MASTER_EDUCATION',

  COMPLETE_HIGHER_MASTER_EDUCATION = 'COMPLETE_HIGHER_MASTER_EDUCATION',
}
