name: sovchilaruzv2
services:
  minio:
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /data:/data
    command: server /data --console-address ":9001"
